name: collman
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  flutter:
    sdk: flutter

  auth_lib: 
    git: 
      url: https://github.com/zorrokid/flutter-auth-lib.git
      ref: 6fa592829f3bfc1be03dc3e2a246b90678d54c25

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
