name: collman
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  flutter:
    sdk: flutter

  auth_lib: 
    git: 
      url: https://github.com/zorrokid/flutter-auth-lib.git
      ref: d35dd0bb6d3b627f46164bd573a4edc177dab891
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
